/*
 * generated by Xtext 2.25.0
 */
package naomod.family.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import naomod.family.FamilyRuntimeModule;
import naomod.family.FamilyStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FamilyIdeSetup extends FamilyStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FamilyRuntimeModule(), new FamilyIdeModule()));
	}
	
}
