/*
 * generated by Xtext 2.24.0
 */
package naomod.family.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFamilyScopeProvider extends DelegatingScopeProvider {
}
