/*
 * generated by Xtext 2.25.0
 */
package naomod.family;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FamilyStandaloneSetup extends FamilyStandaloneSetupGenerated {

	public static void doSetup() {
		new FamilyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
