/*
 * generated by Xtext 2.25.0
 */
package naomod.family;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FamilyRuntimeModule extends AbstractFamilyRuntimeModule {
}
