/**
 * generated by Xtext 2.24.0
 */
package naomod.family.family;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Family</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link naomod.family.family.Family#getMembers <em>Members</em>}</li>
 *   <li>{@link naomod.family.family.Family#getRelations <em>Relations</em>}</li>
 * </ul>
 *
 * @see naomod.family.family.FamilyPackage#getFamily()
 * @model
 * @generated
 */
public interface Family extends EObject
{
  /**
   * Returns the value of the '<em><b>Members</b></em>' containment reference list.
   * The list contents are of type {@link naomod.family.family.Person}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Members</em>' containment reference list.
   * @see naomod.family.family.FamilyPackage#getFamily_Members()
   * @model containment="true"
   * @generated
   */
  EList<Person> getMembers();

  /**
   * Returns the value of the '<em><b>Relations</b></em>' containment reference list.
   * The list contents are of type {@link naomod.family.family.Relation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relations</em>' containment reference list.
   * @see naomod.family.family.FamilyPackage#getFamily_Relations()
   * @model containment="true"
   * @generated
   */
  EList<Relation> getRelations();

} // Family
