/**
 * generated by Xtext 2.24.0
 */
package naomod.family.family;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link naomod.family.family.Relation#getPerson <em>Person</em>}</li>
 *   <li>{@link naomod.family.family.Relation#getParentOne <em>Parent One</em>}</li>
 *   <li>{@link naomod.family.family.Relation#getParentTwo <em>Parent Two</em>}</li>
 * </ul>
 *
 * @see naomod.family.family.FamilyPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends EObject
{
  /**
   * Returns the value of the '<em><b>Person</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person</em>' reference.
   * @see #setPerson(Person)
   * @see naomod.family.family.FamilyPackage#getRelation_Person()
   * @model
   * @generated
   */
  Person getPerson();

  /**
   * Sets the value of the '{@link naomod.family.family.Relation#getPerson <em>Person</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Person</em>' reference.
   * @see #getPerson()
   * @generated
   */
  void setPerson(Person value);

  /**
   * Returns the value of the '<em><b>Parent One</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent One</em>' reference.
   * @see #setParentOne(Person)
   * @see naomod.family.family.FamilyPackage#getRelation_ParentOne()
   * @model
   * @generated
   */
  Person getParentOne();

  /**
   * Sets the value of the '{@link naomod.family.family.Relation#getParentOne <em>Parent One</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent One</em>' reference.
   * @see #getParentOne()
   * @generated
   */
  void setParentOne(Person value);

  /**
   * Returns the value of the '<em><b>Parent Two</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parent Two</em>' reference.
   * @see #setParentTwo(Person)
   * @see naomod.family.family.FamilyPackage#getRelation_ParentTwo()
   * @model
   * @generated
   */
  Person getParentTwo();

  /**
   * Sets the value of the '{@link naomod.family.family.Relation#getParentTwo <em>Parent Two</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parent Two</em>' reference.
   * @see #getParentTwo()
   * @generated
   */
  void setParentTwo(Person value);

} // Relation
